__version__ = "2.0a2"
__author__ = "Rob McMullen"
__author_email__ = "feedback@playermissile.com"
__url__ = "https://github.com/robmcmullen/omnivore"
__bug_report_url__ = "https://github.com/robmcmullen/omnivore/issues"
