__version__ = "0.1"
__author__ = "Rob McMullen"
__author_email__ = "feedback@playermissile.com"
__url__ = "https://github.com/robmcmullen/py6502"
__bug_report_url__ = "https://github.com/robmcmullen/py6502/issues"
