#!/usr/bin/env python

if __name__ == "__main__":
    import sys
    if sys.version_info < (3, 6, 0):
        print("atree requires Python 3.6 or greater to run; this is Python %s" % ".".join([str(v) for v in sys.version_info[0:2]]))
        if sys.version_info[0] == 2:
            print("Python 2 support was dropped with atree 7.0, so you can either use:\n\n    pip install \"atree<7.0\"\n\nto install a version compatible with Python 2, or install Python 3.6 or higher.")
    else:
        import atree
    
        atree.run()
