__version__ = "1.3"
__author__ = "Rob McMullen"
__author_email__ = "feedback@playermissile.com"
__url__ = "https://github.com/robmcmullen/pyatasm"
__bug_report_url__ = "https://github.com/robmcmullen/pyatasm/issues"
